name: python_curso_IMP
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12 # O la versión más reciente que desees, por ejemplo 3.12
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - ipython
  - pip
  - pip:
    - black
    - flake8
